/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javax.swing.JOptionPane;

import controller.OrcamentoController;
import controller.ServicoController;
import dao.exceptions.ExceptionDAO;
import model.Cliente;
import model.Funcionario;
import model.Servico;
import model.Usuario;
import model.enums.TipoServico;
import service.LoginService;

public class CadastroOrcamento extends javax.swing.JFrame {
	private LoginService loginService = LoginService.getInstance();

    public CadastroOrcamento() {
		initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelClickParaVisualizarOrcamentos = new javax.swing.JLabel();
        jPanelContainer = new javax.swing.JPanel();
        jPanelEsquerda = new javax.swing.JPanel();
        jLabelFormulario = new javax.swing.JLabel();
        jLabelLogotipo = new javax.swing.JLabel();
        jPanelFormulario = new javax.swing.JPanel();
        jLabelTipoServ = new javax.swing.JLabel();
        jComboBoxTipoServ = new javax.swing.JComboBox<>();
        jLabelValor = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaDescricao = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldValorCalculado = new javax.swing.JTextField();
        jLabelUnidMonetaria = new javax.swing.JLabel();
        jButtonLimpar = new javax.swing.JButton();
        jButtonSalvar = new javax.swing.JButton();
        jLabelTiulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanelContainer.setBackground(new java.awt.Color(236, 236, 236));

        jPanelEsquerda.setBackground(new java.awt.Color(54, 84, 134));

        jLabelFormulario.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabelFormulario.setForeground(new java.awt.Color(255, 255, 255));
        jLabelFormulario.setText("Formulário de Orçamento");

        jLabelLogotipo.setBackground(new java.awt.Color(54, 84, 134));
        jLabelLogotipo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/logotipo.png"))); // NOI18N

        javax.swing.GroupLayout jPanelEsquerdaLayout = new javax.swing.GroupLayout(jPanelEsquerda);
        jPanelEsquerda.setLayout(jPanelEsquerdaLayout);
        jPanelEsquerdaLayout.setHorizontalGroup(
            jPanelEsquerdaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEsquerdaLayout.createSequentialGroup()
                .addGroup(jPanelEsquerdaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelEsquerdaLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabelLogotipo))
                    .addGroup(jPanelEsquerdaLayout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(jLabelFormulario)))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        jPanelEsquerdaLayout.setVerticalGroup(
            jPanelEsquerdaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEsquerdaLayout.createSequentialGroup()
                .addComponent(jLabelFormulario, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(jLabelLogotipo, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 59, Short.MAX_VALUE))
        );

        jPanelFormulario.setBackground(new java.awt.Color(54, 84, 134));

        jLabelTipoServ.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabelTipoServ.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTipoServ.setText("Selecione o Tipo de Serviço Desejado:");

        jComboBoxTipoServ.setBackground(new java.awt.Color(122, 122, 252));
        jComboBoxTipoServ.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jComboBoxTipoServ.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Adaptação de Site", "Desenvolvimento de Site", "Consultoria" }));
        jComboBoxTipoServ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
					jComboBoxTipoServActionPerformed(evt);
				} catch (ExceptionDAO e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
            }
        });

        jLabelValor.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabelValor.setForeground(new java.awt.Color(255, 255, 255));
        jLabelValor.setText("Descreva com mais detalhes sua real necessidade:");

        jTextAreaDescricao.setColumns(20);
        jTextAreaDescricao.setRows(5);
        jScrollPane1.setViewportView(jTextAreaDescricao);

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Valor estimado (o valor pode ser alterado conforme a negociação).");

        jTextFieldValorCalculado.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldValorCalculado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldValorCalculadoActionPerformed(evt);
            }
        });

        jLabelUnidMonetaria.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabelUnidMonetaria.setForeground(new java.awt.Color(255, 255, 255));
        jLabelUnidMonetaria.setText("R$");

        jButtonLimpar.setBackground(new java.awt.Color(122, 122, 252));
        jButtonLimpar.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jButtonLimpar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonLimpar.setText("Limpar");
        jButtonLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimparActionPerformed(evt);
            }
        });

        jButtonSalvar.setBackground(new java.awt.Color(122, 122, 252));
        jButtonSalvar.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jButtonSalvar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSalvar.setText("Salvar");
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelFormularioLayout = new javax.swing.GroupLayout(jPanelFormulario);
        jPanelFormulario.setLayout(jPanelFormularioLayout);
        jPanelFormularioLayout.setHorizontalGroup(
            jPanelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFormularioLayout.createSequentialGroup()
                .addGroup(jPanelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelFormularioLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jComboBoxTipoServ, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelTipoServ, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 539, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelValor, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelFormularioLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabelUnidMonetaria, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelFormularioLayout.createSequentialGroup()
                                .addComponent(jButtonSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(jButtonLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTextFieldValorCalculado, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(132, Short.MAX_VALUE))
        );
        jPanelFormularioLayout.setVerticalGroup(
            jPanelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFormularioLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabelTipoServ, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxTipoServ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jLabelValor, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldValorCalculado, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelUnidMonetaria))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(jPanelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9))
        );

        jLabelTiulo.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabelTiulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/orcamento.png"))); // NOI18N
        jLabelTiulo.setText("Cadastro de Orçamento");

        javax.swing.GroupLayout jPanelContainerLayout = new javax.swing.GroupLayout(jPanelContainer);
        jPanelContainer.setLayout(jPanelContainerLayout);
        jPanelContainerLayout.setHorizontalGroup(
            jPanelContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelEsquerda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelTiulo)
                    .addComponent(jPanelFormulario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(11, Short.MAX_VALUE))
        );
        jPanelContainerLayout.setVerticalGroup(
            jPanelContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelContainerLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelTiulo, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanelContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelFormulario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelEsquerda, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(711, 711, 711)
                .addComponent(jLabelClickParaVisualizarOrcamentos, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelClickParaVisualizarOrcamentos)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldValorCalculadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldValorCalculadoActionPerformed
        
    }//GEN-LAST:event_jTextFieldValorCalculadoActionPerformed

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
        int resposta = JOptionPane.showConfirmDialog(rootPane, "Tem certeza?");
        
        if (resposta== JOptionPane.YES_OPTION) {
            OrcamentoController controller = new OrcamentoController();
            String tipo = (String) jComboBoxTipoServ.getSelectedItem();
            String descricao = jTextAreaDescricao.getText();
            Usuario user = loginService.getUsuarioLogado(); //view não tem responsabilidade sobre o tipo de user logado.
            if (user instanceof Funcionario) {
                user.setID(13); //ID padrão da administração na tabela clientes.
            }
            boolean sucesso;
            try {
                    sucesso = controller.gerarOrcamento(user, tipo, descricao);

                    if (sucesso) {
                            JOptionPane.showMessageDialog(null, "Orçamento Cadastrado com sucesso.");
                            
                    }
                    else {
                    		if (user == null) {
                    			JOptionPane.showMessageDialog(null, "Usuário não está logado. Não foi possível encontrar.", "Erro", JOptionPane.ERROR_MESSAGE);
                    		}
                            if (descricao.isEmpty()) {
                                    JOptionPane.showMessageDialog(null, "Informe os detalhes na descrição", "Erro", JOptionPane.ERROR_MESSAGE);
                            }
                            else if (descricao.trim().length() >= 500) {
                            	JOptionPane.showMessageDialog(null, "A descrição não pode ultrapassar 500 caracteres. Forneça uma descrição menor.", "Erro", JOptionPane.ERROR_MESSAGE);
                            }
                            JOptionPane.showMessageDialog(null, "Os campos não foram preenchidos corretamente.");
                    }

            } catch(Exception erro) {
                    JOptionPane.showMessageDialog(null, "Erro: " + erro.getMessage());
            }
        }
        else {
            //sistema n faz nada.
        }
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jComboBoxTipoServActionPerformed(java.awt.event.ActionEvent evt) throws ExceptionDAO {//GEN-FIRST:event_jComboBoxTipoServActionPerformed
        OrcamentoController controller = new OrcamentoController();
        String tipo = (String) jComboBoxTipoServ.getSelectedItem();
        TipoServico tipoServ = ServicoController.getTipoSelecionado(tipo);
        
        Double valorServico = Servico.getValorBD(tipoServ);
        jTextFieldValorCalculado.setText(String.format("%.2f", valorServico));
}
//GEN-LAST:event_jComboBoxTipoServActionPerformed

    private void jButtonLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimparActionPerformed

        jComboBoxTipoServ.setSelectedIndex(0); 
        jTextAreaDescricao.setText("");
        jTextFieldValorCalculado.setText("");
    }//GEN-LAST:event_jButtonLimparActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroOrcamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroOrcamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroOrcamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroOrcamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroOrcamento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonLimpar;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JComboBox<String> jComboBoxTipoServ;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelClickParaVisualizarOrcamentos;
    private javax.swing.JLabel jLabelFormulario;
    private javax.swing.JLabel jLabelLogotipo;
    private javax.swing.JLabel jLabelTipoServ;
    private javax.swing.JLabel jLabelTiulo;
    private javax.swing.JLabel jLabelUnidMonetaria;
    private javax.swing.JLabel jLabelValor;
    private javax.swing.JPanel jPanelContainer;
    private javax.swing.JPanel jPanelEsquerda;
    private javax.swing.JPanel jPanelFormulario;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaDescricao;
    private javax.swing.JTextField jTextFieldValorCalculado;
    // End of variables declaration//GEN-END:variables
}
