/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.table.DefaultTableModel;
import controller.CadastroController;
import dao.exceptions.ExceptionDAO;
import model.Cliente;
import model.Funcionario;
import model.Usuario;


public class ConsultarUsuarios extends javax.swing.JFrame {

    /**
     * Creates new form ConsultarUsuarios
     */
    public ConsultarUsuarios() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanelContainer = new javax.swing.JPanel();
        jPanelContainer1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableUsuariosBD = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabelTipoUsuario = new javax.swing.JLabel();
        jTextFieldInputNome = new javax.swing.JTextField();
        jLabelEmail = new javax.swing.JLabel();
        jTextFieldInputEmail = new javax.swing.JTextField();
        jButtonPesquisaNome = new javax.swing.JButton();
        jButtonPesquisaEmail = new javax.swing.JButton();
        jLabelTitulo = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanelContainer.setBackground(new java.awt.Color(54, 84, 134));

        jPanelContainer1.setBackground(new java.awt.Color(54, 84, 134));

        jTableUsuariosBD.setAutoCreateRowSorter(true);
        jTableUsuariosBD.setBackground(new java.awt.Color(236, 234, 234));
        jTableUsuariosBD.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jTableUsuariosBD.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Nome", "Email", "Telefone", "Endereco", "Tipo Usuário", "CNPJ", "Cargo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTableUsuariosBD.setGridColor(new java.awt.Color(204, 204, 204));
        jScrollPane1.setViewportView(jTableUsuariosBD);

        jButton1.setBackground(new java.awt.Color(83, 92, 145));
        jButton1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Sair");

        jLabelTipoUsuario.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabelTipoUsuario.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTipoUsuario.setText("Consulta por nome");

        jTextFieldInputNome.setToolTipText("informe o nome do(s) usuário(s)");

        jLabelEmail.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabelEmail.setForeground(new java.awt.Color(255, 255, 255));
        jLabelEmail.setText("Consulta por email");

        jTextFieldInputEmail.setToolTipText("informe o email.");

        jButtonPesquisaNome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/consultarIcon.png"))); // NOI18N
        jButtonPesquisaNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisaNomeActionPerformed(evt);
            }
        });

        jButtonPesquisaEmail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/consultarIcon.png"))); // NOI18N
        jButtonPesquisaEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisaEmailActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelContainer1Layout = new javax.swing.GroupLayout(jPanelContainer1);
        jPanelContainer1.setLayout(jPanelContainer1Layout);
        jPanelContainer1Layout.setHorizontalGroup(
            jPanelContainer1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelContainer1Layout.createSequentialGroup()
                .addGroup(jPanelContainer1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelContainer1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 828, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelContainer1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelEmail)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldInputEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonPesquisaEmail))
                    .addGroup(jPanelContainer1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelTipoUsuario)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldInputNome, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonPesquisaNome))
                    .addGroup(jPanelContainer1Layout.createSequentialGroup()
                        .addGap(331, 331, 331)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanelContainer1Layout.setVerticalGroup(
            jPanelContainer1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelContainer1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanelContainer1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTipoUsuario)
                    .addComponent(jTextFieldInputNome, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonPesquisaNome))
                .addGap(21, 21, 21)
                .addGroup(jPanelContainer1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelContainer1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldInputEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelEmail))
                    .addComponent(jButtonPesquisaEmail))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        jLabelTitulo.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/consultar.png"))); // NOI18N
        jLabelTitulo.setText("Consultar Usuários");

        javax.swing.GroupLayout jPanelContainerLayout = new javax.swing.GroupLayout(jPanelContainer);
        jPanelContainer.setLayout(jPanelContainerLayout);
        jPanelContainerLayout.setHorizontalGroup(
            jPanelContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelContainerLayout.createSequentialGroup()
                .addGap(0, 12, Short.MAX_VALUE)
                .addComponent(jPanelContainer1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanelContainerLayout.createSequentialGroup()
                .addGap(304, 304, 304)
                .addComponent(jLabelTitulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelContainerLayout.setVerticalGroup(
            jPanelContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitulo)
                .addGap(45, 45, 45)
                .addComponent(jPanelContainer1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(226, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelContainer, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonPesquisaEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisaEmailActionPerformed
        // TODO add your handling code here:
        CadastroController controller = new CadastroController();
        String email = jTextFieldInputEmail.getText();

        DefaultTableModel tableModel = (DefaultTableModel) jTableUsuariosBD.getModel();
        tableModel.setRowCount(0);

        try {
            ArrayList<Usuario> usuarios = controller.consultarUsuarios(email, 2);
            for (Usuario user : usuarios) {
                if (user instanceof Cliente) {
                    Cliente cliente = (Cliente) user;
                    tableModel.addRow(new Object[]{
                        cliente.getNomeCompleto(),
                        cliente.getEmail(),
                        cliente.getTelefone(),
                        cliente.getEndereco(),
                        "Cliente",
                        cliente.getCNPJ(),
                        "N/A"
                    });
                } else {
                    Funcionario funcionario = (Funcionario) user;
                    tableModel.addRow(new Object[]{
                        funcionario.getNomeCompleto(),
                        funcionario.getEmail(),
                        funcionario.getTelefone(),
                        null,
                        "Funcionario",
                        null,
                        funcionario.getCargo()
                    });
                }
            }
        } catch (ExceptionDAO e) {
            Logger.getLogger(ConsultarUsuarios.class.getName()).log(Level.SEVERE, "Ocorreu um erro ao consultar usuários", e);
        }
        
    }//GEN-LAST:event_jButtonPesquisaEmailActionPerformed

    private void jButtonPesquisaNomeActionPerformed(java.awt.event.ActionEvent evt) {                                                    
        CadastroController controller = new CadastroController();
        String nome = jTextFieldInputNome.getText();

        DefaultTableModel tableModel = (DefaultTableModel) jTableUsuariosBD.getModel();
        tableModel.setRowCount(0);

        try {
            ArrayList<Usuario> usuarios = controller.consultarUsuarios(nome, 1);
            for (Usuario user : usuarios) {
                if (user instanceof Cliente) {
                    Cliente cliente = (Cliente) user;
                    tableModel.addRow(new Object[]{
                        cliente.getNomeCompleto(),
                        cliente.getEmail(),
                        cliente.getTelefone(),
                        cliente.getEndereco(),
                        "Cliente",
                        cliente.getCNPJ(),
                        "N/A"
                    });
                } else {
                    Funcionario funcionario = (Funcionario) user;
                    tableModel.addRow(new Object[]{
                        funcionario.getNomeCompleto(),
                        funcionario.getEmail(),
                        funcionario.getTelefone(),
                        null,
                        "Funcionario",
                        null,
                        funcionario.getCargo()
                    });
                }
            }
        } catch (ExceptionDAO e) {
            Logger.getLogger(ConsultarUsuarios.class.getName()).log(Level.SEVERE, "Ocorreu um erro ao consultar usuários", e);
        }
    }


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultarUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultarUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultarUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultarUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsultarUsuarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonPesquisaEmail;
    private javax.swing.JButton jButtonPesquisaNome;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelTipoUsuario;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelContainer;
    private javax.swing.JPanel jPanelContainer1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableUsuariosBD;
    private javax.swing.JTextField jTextFieldInputEmail;
    private javax.swing.JTextField jTextFieldInputNome;
    // End of variables declaration//GEN-END:variables
}
