/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.ServicoController;
import dao.exceptions.ExceptionDAO;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Servico;

public class ConsultarServicos extends javax.swing.JFrame {

    /**
     * Creates new form ConsultarServicos
     */
    public ConsultarServicos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanelContainer = new javax.swing.JPanel();
        jPanelContainer1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableServicosBD = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabelTipoUsuario = new javax.swing.JLabel();
        jTextFieldInputNome = new javax.swing.JTextField();
        jButtonPesquisaNome = new javax.swing.JButton();
        jLabelTitulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelContainer.setBackground(new java.awt.Color(54, 84, 134));
        jPanelContainer.setLayout(new java.awt.GridBagLayout());

        jPanelContainer1.setBackground(new java.awt.Color(54, 84, 134));

        jTableServicosBD.setAutoCreateRowSorter(true);
        jTableServicosBD.setBackground(new java.awt.Color(236, 234, 234));
        jTableServicosBD.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jTableServicosBD.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nome", "Valor Padrão", "Tipo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Double.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTableServicosBD.setGridColor(new java.awt.Color(204, 204, 204));
        jScrollPane1.setViewportView(jTableServicosBD);

        jButton1.setBackground(new java.awt.Color(83, 92, 145));
        jButton1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Sair");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabelTipoUsuario.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabelTipoUsuario.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTipoUsuario.setText("Consulta por nome");

        jTextFieldInputNome.setToolTipText("informe o nome do servico");

        jButtonPesquisaNome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/consultarIcon.png"))); // NOI18N
        jButtonPesquisaNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisaNomeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelContainer1Layout = new javax.swing.GroupLayout(jPanelContainer1);
        jPanelContainer1.setLayout(jPanelContainer1Layout);
        jPanelContainer1Layout.setHorizontalGroup(
            jPanelContainer1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelContainer1Layout.createSequentialGroup()
                .addGroup(jPanelContainer1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelContainer1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelTipoUsuario)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldInputNome, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonPesquisaNome))
                    .addGroup(jPanelContainer1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 637, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelContainer1Layout.createSequentialGroup()
                        .addGap(243, 243, 243)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(197, Short.MAX_VALUE))
        );
        jPanelContainer1Layout.setVerticalGroup(
            jPanelContainer1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelContainer1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanelContainer1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTipoUsuario)
                    .addComponent(jTextFieldInputNome, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonPesquisaNome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 191;
        gridBagConstraints.ipady = 20;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(45, 0, 52, 0);
        jPanelContainer.add(jPanelContainer1, gridBagConstraints);

        jLabelTitulo.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/consultar.png"))); // NOI18N
        jLabelTitulo.setText("Consultar Serviços");
        jPanelContainer.add(jLabelTitulo, new java.awt.GridBagConstraints());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelContainer, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonPesquisaNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisaNomeActionPerformed
        String input = jTextFieldInputNome.getText();
        ServicoController controller = new ServicoController();
        DefaultTableModel tableModel = (DefaultTableModel) jTableServicosBD.getModel();
        tableModel.setRowCount(0);
        try {
            ArrayList<Servico> servicos = controller.visualizarServicos(input);
            for(Servico serv : servicos) {
                tableModel.addRow(new Object[]{serv.getNome(), serv.getValor(), serv.getTipo().toString()});
            }
        } catch(ExceptionDAO | SQLException e) {
            JOptionPane.showMessageDialog(null, "Erro na consulta: " + e.getMessage());
        }
        
    }//GEN-LAST:event_jButtonPesquisaNomeActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultarServicos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultarServicos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultarServicos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultarServicos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsultarServicos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonPesquisaNome;
    private javax.swing.JLabel jLabelTipoUsuario;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JPanel jPanelContainer;
    private javax.swing.JPanel jPanelContainer1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableServicosBD;
    private javax.swing.JTextField jTextFieldInputNome;
    // End of variables declaration//GEN-END:variables
}
