/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javax.swing.JOptionPane;

import controller.CadastroController;
import dao.exceptions.ExceptionDAO;
import model.Cliente;
import model.Funcionario;
import model.Usuario;
import service.LoginService;


public class EditarPerfil extends javax.swing.JFrame {
	private static final long serialVersionUID = 1L;
	private LoginService loginService = LoginService.getInstance();
	private Usuario usuarioLogado = loginService.getUsuarioLogado();

    public EditarPerfil() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanelContainer = new javax.swing.JPanel();
        jLabelTitulo = new javax.swing.JLabel();
        jPanelCadastroUsuario = new javax.swing.JPanel();
        jLabelEmail = new javax.swing.JLabel();
        jLabelNome1 = new javax.swing.JLabel();
        jLabelTelefone = new javax.swing.JLabel();
        jLabelSenha = new javax.swing.JLabel();
        jTextFieldEmail = new javax.swing.JTextField();
        jTextFieldNome = new javax.swing.JTextField();
        jButtonLimpar = new javax.swing.JButton();
        jButtonEditar = new javax.swing.JButton();
        jLabelCnpj = new javax.swing.JLabel();
        jFormattedTextFieldTelefone = new javax.swing.JFormattedTextField();
        jFormattedTextCNPJ = new javax.swing.JFormattedTextField();
        jPasswordField = new javax.swing.JPasswordField();
        jTextFieldCargo = new javax.swing.JTextField();
        jLabelCargo = new javax.swing.JLabel();
        jLabelEndereco = new javax.swing.JLabel();
        jTextFieldEndereco = new javax.swing.JTextField();
        jButtonMeuPerfil = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanelContainer.setBackground(new java.awt.Color(54, 84, 134));
        jPanelContainer.setLayout(new java.awt.GridBagLayout());

        jLabelTitulo.setBackground(new java.awt.Color(0, 0, 0));
        jLabelTitulo.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/editarPerfil.png"))); // NOI18N
        jLabelTitulo.setText("Editar Perfil");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 165;
        gridBagConstraints.ipady = -14;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 243, 0, 0);
        jPanelContainer.add(jLabelTitulo, gridBagConstraints);

        jPanelCadastroUsuario.setBackground(new java.awt.Color(236, 236, 236));
        jPanelCadastroUsuario.setPreferredSize(new java.awt.Dimension(780, 400));

        jLabelEmail.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        jLabelEmail.setText("E-mail");

        jLabelNome1.setBackground(new java.awt.Color(255, 255, 255));
        jLabelNome1.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        jLabelNome1.setText("Nome Completo:");

        jLabelTelefone.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        jLabelTelefone.setText("Telefone");

        jLabelSenha.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        jLabelSenha.setText("Senha");

        jTextFieldEmail.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jTextFieldEmail.setToolTipText("");
        jTextFieldEmail.setMinimumSize(new java.awt.Dimension(64, 25));
        jTextFieldEmail.setPreferredSize(new java.awt.Dimension(64, 25));

        jTextFieldNome.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jTextFieldNome.setToolTipText("Digite o seu nome completo");
        jTextFieldNome.setPreferredSize(new java.awt.Dimension(64, 25));

        jButtonLimpar.setBackground(new java.awt.Color(83, 92, 145));
        jButtonLimpar.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jButtonLimpar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonLimpar.setText("Limpar");
        jButtonLimpar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonLimpar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimparActionPerformed(evt);
            }
        });

        jButtonEditar.setBackground(new java.awt.Color(83, 92, 145));
        jButtonEditar.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jButtonEditar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonEditar.setText("Salvar");
        jButtonEditar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonEditar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarActionPerformed(evt);
            }
        });

        jLabelCnpj.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        jLabelCnpj.setText("CNPJ");

        try {
            jFormattedTextFieldTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldTelefone.setToolTipText("");
        jFormattedTextFieldTelefone.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N

        try {
            jFormattedTextCNPJ.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###/####-##     ")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jPasswordField.setText("jPasswordField1");

        jTextFieldCargo.setToolTipText("Cargo do funcionário");

        jLabelCargo.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        jLabelCargo.setText("Cargo");

        jLabelEndereco.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        jLabelEndereco.setText("Endereco");

        jTextFieldEndereco.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jTextFieldEndereco.setToolTipText("");
        jTextFieldEndereco.setMinimumSize(new java.awt.Dimension(64, 25));
        jTextFieldEndereco.setPreferredSize(new java.awt.Dimension(64, 25));

        jButtonMeuPerfil.setBackground(new java.awt.Color(83, 92, 145));
        jButtonMeuPerfil.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jButtonMeuPerfil.setForeground(new java.awt.Color(255, 255, 255));
        jButtonMeuPerfil.setText("Meu Perfil");
        jButtonMeuPerfil.setToolTipText("");
        jButtonMeuPerfil.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonMeuPerfil.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonMeuPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMeuPerfilActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelCadastroUsuarioLayout = new javax.swing.GroupLayout(jPanelCadastroUsuario);
        jPanelCadastroUsuario.setLayout(jPanelCadastroUsuarioLayout);
        jPanelCadastroUsuarioLayout.setHorizontalGroup(
            jPanelCadastroUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCadastroUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCadastroUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCadastroUsuarioLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonMeuPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(jButtonEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(jButtonLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanelCadastroUsuarioLayout.createSequentialGroup()
                        .addGroup(jPanelCadastroUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanelCadastroUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanelCadastroUsuarioLayout.createSequentialGroup()
                                    .addComponent(jLabelNome1)
                                    .addGap(61, 61, 61)
                                    .addComponent(jTextFieldNome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(jPanelCadastroUsuarioLayout.createSequentialGroup()
                                    .addGroup(jPanelCadastroUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanelCadastroUsuarioLayout.createSequentialGroup()
                                            .addComponent(jLabelEmail)
                                            .addGap(151, 151, 151))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelCadastroUsuarioLayout.createSequentialGroup()
                                            .addComponent(jLabelCnpj)
                                            .addGap(14, 14, 14)))
                                    .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 526, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanelCadastroUsuarioLayout.createSequentialGroup()
                                .addGroup(jPanelCadastroUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanelCadastroUsuarioLayout.createSequentialGroup()
                                        .addGroup(jPanelCadastroUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabelSenha)
                                            .addComponent(jLabelEndereco))
                                        .addGap(125, 125, 125))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelCadastroUsuarioLayout.createSequentialGroup()
                                        .addGroup(jPanelCadastroUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabelTelefone, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabelCargo, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(jPanelCadastroUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldEndereco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jPasswordField)
                                    .addComponent(jFormattedTextFieldTelefone)
                                    .addComponent(jFormattedTextCNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, 526, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 526, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(24, Short.MAX_VALUE))))
        );
        jPanelCadastroUsuarioLayout.setVerticalGroup(
            jPanelCadastroUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCadastroUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCadastroUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNome1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelCadastroUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelCadastroUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSenha)
                    .addComponent(jPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelCadastroUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEndereco)
                    .addComponent(jTextFieldEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelCadastroUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTelefone)
                    .addComponent(jFormattedTextFieldTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelCadastroUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCnpj)
                    .addComponent(jFormattedTextCNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelCadastroUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCargo)
                    .addComponent(jTextFieldCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 105, Short.MAX_VALUE)
                .addGroup(jPanelCadastroUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonMeuPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 18;
        gridBagConstraints.ipady = 99;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 6, 6, 36);
        jPanelContainer.add(jPanelCadastroUsuario, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelContainer, javax.swing.GroupLayout.DEFAULT_SIZE, 801, Short.MAX_VALUE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelContainer, javax.swing.GroupLayout.DEFAULT_SIZE, 547, Short.MAX_VALUE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimparActionPerformed
        jTextFieldNome.setText("");
        jTextFieldEmail.setText("");
        jPasswordField.setText("");
        jTextFieldEndereco.setText("");
        jFormattedTextFieldTelefone.setText("");
        jFormattedTextCNPJ.setText("");
        jTextFieldCargo.setText("");
    }

    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed
        //update.
    	CadastroController controller = new CadastroController();
    	boolean sucesso;
    	try {
			int escolha = JOptionPane.showConfirmDialog(null, "Tem certeza?");
			if (escolha == JOptionPane.YES_OPTION) {
				usuarioLogado.setNomeCompleto(jTextFieldNome.getText());
				usuarioLogado.setEmail(jTextFieldEmail.getText());
				char[] passwordChars = jPasswordField.getPassword();
	            String novaSenha = new String(passwordChars);
				usuarioLogado.setSenha(novaSenha);
				usuarioLogado.setTelefone(jFormattedTextFieldTelefone.getText().replaceAll("[^\\d]", ""));
				
				if (usuarioLogado instanceof Funcionario) {
					Funcionario func = (Funcionario) usuarioLogado;
					func.setCargo(jTextFieldCargo.getText());
				} else {
					Cliente cliente = (Cliente) usuarioLogado;
					cliente.setCNPJ(jFormattedTextCNPJ.getText().replaceAll("[^0-9]", ""));
				}
				
				sucesso = controller.editarPerfil(usuarioLogado);
				
				if(sucesso) 
					JOptionPane.showMessageDialog(this, "Perfil alterado com sucesso", "Edição de Perfil.", JOptionPane.INFORMATION_MESSAGE);
				else 
					JOptionPane.showMessageDialog(this, "Erro. Por favor forneça dados válidos.", "Edição de Perfil.", JOptionPane.ERROR_MESSAGE);
			}
			else
				JOptionPane.showMessageDialog(this, "Ação cancelada", "Edição de Perfil.", JOptionPane.INFORMATION_MESSAGE);;
				
		} catch (ExceptionDAO e) {
			// TODO Auto-generated catch block
			JOptionPane.showMessageDialog(this, "Erro ao editar perfil: " + e.getMessage(), "Edição de Perfil.", JOptionPane.ERROR_MESSAGE);
		}
    }

    private void jButtonMeuPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMeuPerfilActionPerformed
        Usuario user = usuarioLogado;
        if (user instanceof Funcionario) {
            Funcionario func = (Funcionario) user;
            jFormattedTextCNPJ.setVisible(false);
            jTextFieldCargo.setText(func.getCargo());
        }
        else {
            Cliente cliente = (Cliente) user;
            jTextFieldCargo.setVisible(false);
            jFormattedTextCNPJ.setText(cliente.getCNPJ());
        }
        jTextFieldNome.setText(user.getNomeCompleto());
        jTextFieldEmail.setText(user.getEmail());
        jPasswordField.setText(user.getSenha());
        jTextFieldEndereco.setText(user.getEmail());
        jFormattedTextFieldTelefone.setText(user.getTelefone());
    }//GEN-LAST:event_jButtonMeuPerfilActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditarPerfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditarPerfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditarPerfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditarPerfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditarPerfil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonLimpar;
    private javax.swing.JButton jButtonMeuPerfil;
    private javax.swing.JFormattedTextField jFormattedTextCNPJ;
    private javax.swing.JFormattedTextField jFormattedTextFieldTelefone;
    private javax.swing.JLabel jLabelCargo;
    private javax.swing.JLabel jLabelCnpj;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelEndereco;
    private javax.swing.JLabel jLabelNome1;
    private javax.swing.JLabel jLabelSenha;
    private javax.swing.JLabel jLabelTelefone;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JPanel jPanelCadastroUsuario;
    private javax.swing.JPanel jPanelContainer;
    private javax.swing.JPasswordField jPasswordField;
    private javax.swing.JTextField jTextFieldCargo;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldEndereco;
    private javax.swing.JTextField jTextFieldNome;
    // End of variables declaration//GEN-END:variables
}
