/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.OrcamentoController;
import dao.exceptions.ExceptionDAO;
import java.awt.Color;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Cliente;
import model.Funcionario;
import model.Orcamento;
import model.Usuario;
import service.LoginService;


public class GerenciarOrcamentos extends javax.swing.JFrame {
	private static final long serialVersionUID = 1L;
	OrcamentoController controllerOrc = new OrcamentoController();
	private LoginService loginService = LoginService.getInstance();
	private Usuario usuarioLogado = loginService.getUsuarioLogado();
	
    /**
     * Creates new form GerenciarOrcamentos
     */
    public GerenciarOrcamentos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanelContainer = new javax.swing.JPanel();
        jLabelTitulo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableOrcamentosBD = new javax.swing.JTable();
        jButtonEditarOrc = new javax.swing.JButton();
        jButtonConcluirStatus = new javax.swing.JButton();
        jButtonCancelarStatus = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButtonConsultarOrcamentos = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setSize(jPanelContainer.getSize());

        jPanelContainer.setBackground(new java.awt.Color(54, 84, 134));

        jLabelTitulo.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/orcamento.png"))); // NOI18N
        jLabelTitulo.setText("Gerenciamento de Orçamentos");

        jTableOrcamentosBD.setAutoCreateRowSorter(true);
        jTableOrcamentosBD.setBackground(new java.awt.Color(236, 234, 234));
        jTableOrcamentosBD.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jTableOrcamentosBD.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Cliente", "CNPJ", "Valor Total", "Tipo Serviço", "Status", "Vendedor", "Descricao", "Data", "Validade", "Selecionar"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTableOrcamentosBD.setGridColor(new java.awt.Color(204, 204, 204));
        jScrollPane1.setViewportView(jTableOrcamentosBD);
        jTableOrcamentosBD.getAccessibleContext().setAccessibleName("");

        jButtonEditarOrc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/editarIcon.png"))); // NOI18N
        jButtonEditarOrc.setToolTipText("Editar dados do orcamento");
        jButtonEditarOrc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarOrcActionPerformed(evt);
            }
        });

        jButtonConcluirStatus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/concluirIcon.png"))); // NOI18N
        jButtonConcluirStatus.setToolTipText("Concluir status");
        jButtonConcluirStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
					jButtonConcluirStatusActionPerformed(evt);
				} catch (ExceptionDAO e) {
					e.printStackTrace();
				}
            }
        });

        jButtonCancelarStatus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cancelarIcon.png"))); // NOI18N
        jButtonCancelarStatus.setToolTipText("Cancelar status");
        jButtonCancelarStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarStatusActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(83, 92, 145));
        jButton1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Sair");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButtonConsultarOrcamentos.setBackground(new java.awt.Color(83, 92, 145));
        jButtonConsultarOrcamentos.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jButtonConsultarOrcamentos.setForeground(new java.awt.Color(255, 255, 255));
        jButtonConsultarOrcamentos.setText("Consultar");
        jButtonConsultarOrcamentos.setToolTipText("realiza uma consulta no banco de dados com todos os orçamentos.");
        jButtonConsultarOrcamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConsultarOrcamentosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelContainerLayout = new javax.swing.GroupLayout(jPanelContainer);
        jPanelContainer.setLayout(jPanelContainerLayout);
        jPanelContainerLayout.setHorizontalGroup(
            jPanelContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelContainerLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonConcluirStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonEditarOrc, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonCancelarStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
            .addGroup(jPanelContainerLayout.createSequentialGroup()
                .addGroup(jPanelContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelContainerLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 828, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelContainerLayout.createSequentialGroup()
                        .addGap(222, 222, 222)
                        .addComponent(jButtonConsultarOrcamentos, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelContainerLayout.createSequentialGroup()
                        .addGap(225, 225, 225)
                        .addComponent(jLabelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanelContainerLayout.setVerticalGroup(
            jPanelContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonConcluirStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonEditarOrc, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCancelarStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 333, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanelContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonConsultarOrcamentos, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(166, 166, 166))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(416, 416, 416))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanelContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jPanelContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 789, Short.MAX_VALUE))
        );

        pack();
    }

    private void jButtonEditarOrcActionPerformed(java.awt.event.ActionEvent evt) {                                                 
    	DefaultTableModel model = (DefaultTableModel) jTableOrcamentosBD.getModel();
        int[] selectedRows = jTableOrcamentosBD.getSelectedRows();
        if (jTableOrcamentosBD.isEditing()) {
            jTableOrcamentosBD.getCellEditor().stopCellEditing();
        }
        if (selectedRows.length == 0) {
            JOptionPane.showMessageDialog(this, "Por favor, selecione pelo menos um orçamento para editar.", "Nenhum orçamento selecionado", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        for (int row : selectedRows) {
            Integer orcID = (Integer) model.getValueAt(row, 0);
            Double novoValor = (Double) model.getValueAt(row, 3);
            String descricao = (String) model.getValueAt(row, 7);
            String emailVendedor = (String) model.getValueAt(row, 6);
            try {
            	Funcionario func = (Funcionario) usuarioLogado;
            	//controllerOrc.editarOrcamento(orcID, novoValor, descricao, emailVendedor);
            	func.editarOrcamento(orcID, novoValor, descricao, emailVendedor);
            } catch (ExceptionDAO e) {
            	JOptionPane.showMessageDialog(this, "Erro ao concluir o status do orçamento. ID: " + orcID, e.getMessage(), JOptionPane.ERROR_MESSAGE);
            }
        }
        jButtonConsultarOrcamentosActionPerformed(evt); //atualiza tabela.
        model.fireTableDataChanged();
    }

    private void jButtonConcluirStatusActionPerformed(java.awt.event.ActionEvent evt) throws ExceptionDAO {   
        DefaultTableModel model = (DefaultTableModel) jTableOrcamentosBD.getModel();
        int[] selectedRows = jTableOrcamentosBD.getSelectedRows();
       
        if (selectedRows.length == 0) {
            JOptionPane.showMessageDialog(this, "Por favor, selecione pelo menos um orçamento para concluir o status.", "Nenhum orçamento selecionado", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        for (int row : selectedRows) {
            // Verifica se o orçamento está selecionado (coluna "Selecionar")
            Integer orcID = (Integer) model.getValueAt(row, 0);
            try {
            	controllerOrc.alterarStatusOrcamento(orcID, 3);
            } catch (ExceptionDAO e) {
            	JOptionPane.showMessageDialog(this, "Erro ao concluir o status do orçamento. ID: " + orcID, e.getMessage(), JOptionPane.ERROR_MESSAGE);
            }
        }
        jButtonConsultarOrcamentosActionPerformed(evt); //atualiza tabela.
        model.fireTableDataChanged();
    }

    private void jButtonCancelarStatusActionPerformed(java.awt.event.ActionEvent evt) {                                                      
        DefaultTableModel model = (DefaultTableModel) jTableOrcamentosBD.getModel();
        int[] selectedRows = jTableOrcamentosBD.getSelectedRows();
       
        if (selectedRows.length == 0) {
            JOptionPane.showMessageDialog(this, "Por favor, selecione pelo menos um orçamento para cancelar o status.", "Nenhum orçamento selecionado", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        for (int row : selectedRows) {
            Integer orcID = (Integer) model.getValueAt(row, 0);
            try {
            	controllerOrc.alterarStatusOrcamento(orcID, 2); //cancelar
            } catch (ExceptionDAO e) {
            	JOptionPane.showMessageDialog(this, "Erro ao cancelar o status do orçamento. ID: " + orcID, e.getMessage(), JOptionPane.ERROR_MESSAGE);
            }
        }
        jButtonConsultarOrcamentosActionPerformed(evt); //atualiza tabela.
        model.fireTableDataChanged();
    }

    private void jButtonConsultarOrcamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConsultarOrcamentosActionPerformed
        DefaultTableModel tableModel = (DefaultTableModel) jTableOrcamentosBD.getModel();
        tableModel.setRowCount(0);
        try {
           ArrayList<Orcamento> listaOrcs = OrcamentoController.listarOrcamentos();
           for(Orcamento orc : listaOrcs) {
               Usuario user = orc.getUsuario();
               
               if(user instanceof Cliente) {
            	   Cliente cliente = (Cliente) user;
            	   tableModel.addRow(new Object[] {
            			   orc.getID(),
            			   cliente.getNomeCompleto(),
            			   cliente.getCNPJ(),
            			   orc.getValor(),
            			   orc.getTipoServico().toString(),
            			   orc.getStatus().toString(),
            			   orc.getEmailVendedor(),
            			   orc.getDescricao(),
            			   orc.getDataCriacao(),
            			   orc.getDataValidade()});
               }
               else {
            	   tableModel.addRow(new Object[] {
            			   "admin: " + user.getNomeCompleto(),
            			   "N/A",
            			   orc.getValor(),
            			   orc.getTipoServico().toString(),
            			   orc.getStatus().toString(),
            			   orc.getEmailVendedor(),
            			   orc.getDescricao(),
            			   orc.getDataCriacao(),
            			   orc.getDataValidade()});
               }
  
               jTableOrcamentosBD.setModel(tableModel);
           }
               
           
        } catch (ExceptionDAO ex) {
            Logger.getLogger(GerenciarOrcamentos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonConsultarOrcamentosActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GerenciarOrcamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GerenciarOrcamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GerenciarOrcamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GerenciarOrcamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GerenciarOrcamentos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler filler1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonCancelarStatus;
    private javax.swing.JButton jButtonConcluirStatus;
    private javax.swing.JButton jButtonConsultarOrcamentos;
    private javax.swing.JButton jButtonEditarOrc;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JPanel jPanelContainer;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableOrcamentosBD;
    // End of variables declaration//GEN-END:variables
}
