/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.BorderLayout;
import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

import service.LoginService;


public class TelaAdm extends javax.swing.JFrame {
	private LoginService loginService = LoginService.getInstance();
	
    public TelaAdm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelTelaAdm = new javax.swing.JPanel();
        jLabelLogotipo = new javax.swing.JLabel();
        jButtonLogout = new javax.swing.JButton();
        jLabelNomeUsuarioLogado = new javax.swing.JLabel();
        jMenuBarAdministracao = new javax.swing.JMenuBar();
        jMenuGerenciarServicos = new javax.swing.JMenu();
        jMenuItemEditarServico = new javax.swing.JMenuItem();
        jMenuItemVisualizarServicos = new javax.swing.JMenuItem();
        jMenuUsuarios = new javax.swing.JMenu();
        jMenuItemUsuarios = new javax.swing.JMenuItem();
        jMenuItemCadastrarUsuario = new javax.swing.JMenuItem();
        jMenuItemEditarPerfil = new javax.swing.JMenuItem();
        jMenuOrcamentos = new javax.swing.JMenu();
        jMenuItemListaOrcamentos = new javax.swing.JMenuItem();
        jMenuItemGerarOrc = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Administracao");

        jPanelTelaAdm.setBackground(new java.awt.Color(54, 84, 134));
        jPanelTelaAdm.setPreferredSize(new java.awt.Dimension(800, 600));

        jLabelLogotipo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelLogotipo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/logotipo.png"))); // NOI18N
        jLabelLogotipo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jButtonLogout.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButtonLogout.setText("Logout");
        jButtonLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLogoutActionPerformed(evt);
            }
        });

        jLabelNomeUsuarioLogado.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabelNomeUsuarioLogado.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNomeUsuarioLogado.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelNomeUsuarioLogado.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout jPanelTelaAdmLayout = new javax.swing.GroupLayout(jPanelTelaAdm);
        jPanelTelaAdm.setLayout(jPanelTelaAdmLayout);
        jPanelTelaAdmLayout.setHorizontalGroup(
            jPanelTelaAdmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTelaAdmLayout.createSequentialGroup()
                .addGroup(jPanelTelaAdmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelTelaAdmLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelNomeUsuarioLogado, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelTelaAdmLayout.createSequentialGroup()
                        .addGap(266, 266, 266)
                        .addComponent(jLabelLogotipo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 167, Short.MAX_VALUE)
                        .addComponent(jButtonLogout)))
                .addGap(24, 24, 24))
        );
        jPanelTelaAdmLayout.setVerticalGroup(
            jPanelTelaAdmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTelaAdmLayout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(jLabelLogotipo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(253, 253, 253))
            .addGroup(jPanelTelaAdmLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelNomeUsuarioLogado, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jButtonLogout)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabelNomeUsuarioLogado.setText("User: " + loginService.getUsuarioLogado().getEmail());

        getContentPane().add(jPanelTelaAdm, java.awt.BorderLayout.CENTER);

        jMenuBarAdministracao.setBackground(new java.awt.Color(54, 84, 134));
        jMenuBarAdministracao.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(236, 236, 236)));
        jMenuBarAdministracao.setToolTipText("");

        jMenuGerenciarServicos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/adm.png"))); // NOI18N
        jMenuGerenciarServicos.setText("Servicos");
        jMenuGerenciarServicos.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N

        jMenuItemEditarServico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/editar.png"))); // NOI18N
        jMenuItemEditarServico.setText("Editar Servicos");
        jMenuItemEditarServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemEditarServicoActionPerformed(evt);
            }
        });
        jMenuGerenciarServicos.add(jMenuItemEditarServico);

        jMenuItemVisualizarServicos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/consultar.png"))); // NOI18N
        jMenuItemVisualizarServicos.setText("Visualizar");
        jMenuItemVisualizarServicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemVisualizarServicosActionPerformed(evt);
            }
        });
        jMenuGerenciarServicos.add(jMenuItemVisualizarServicos);

        jMenuBarAdministracao.add(jMenuGerenciarServicos);

        jMenuUsuarios.setText("Usuarios");
        jMenuUsuarios.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N

        jMenuItemUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/consultar.png"))); // NOI18N
        jMenuItemUsuarios.setText("Exibir Usuarios");
        jMenuItemUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemUsuariosActionPerformed(evt);
            }
        });
        jMenuUsuarios.add(jMenuItemUsuarios);

        jMenuItemCadastrarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/adicionar.png"))); // NOI18N
        jMenuItemCadastrarUsuario.setText("Cadastrar");
        jMenuItemCadastrarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadastrarUsuarioActionPerformed(evt);
            }
        });
        jMenuUsuarios.add(jMenuItemCadastrarUsuario);

        jMenuItemEditarPerfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/editarPerfil.png"))); // NOI18N
        jMenuItemEditarPerfil.setText("Editar Perfil");
        jMenuItemEditarPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemEditarPerfilActionPerformed(evt);
            }
        });
        jMenuUsuarios.add(jMenuItemEditarPerfil);

        jMenuBarAdministracao.add(jMenuUsuarios);

        jMenuOrcamentos.setText("Orcamentos");
        jMenuOrcamentos.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N

        jMenuItemListaOrcamentos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/orcamento.png"))); // NOI18N
        jMenuItemListaOrcamentos.setText("Lista Orcamentos");
        jMenuItemListaOrcamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemListaOrcamentosActionPerformed(evt);
            }
        });
        jMenuOrcamentos.add(jMenuItemListaOrcamentos);

        jMenuItemGerarOrc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/orcamento.png"))); // NOI18N
        jMenuItemGerarOrc.setText("Gerar Orcamento");
        jMenuItemGerarOrc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemGerarOrcActionPerformed(evt);
            }
        });
        jMenuOrcamentos.add(jMenuItemGerarOrc);

        jMenuBarAdministracao.add(jMenuOrcamentos);

        setJMenuBar(jMenuBarAdministracao);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemCadastrarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadastrarUsuarioActionPerformed
       TelaCadastroUsuarios cadastro = new TelaCadastroUsuarios();
       cadastro.setVisible(true);
    }//GEN-LAST:event_jMenuItemCadastrarUsuarioActionPerformed

    private void jMenuItemListaOrcamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemListaOrcamentosActionPerformed
        GerenciarOrcamentos telaOrcamentos = new GerenciarOrcamentos();
        telaOrcamentos.setVisible(true);
    }//GEN-LAST:event_jMenuItemListaOrcamentosActionPerformed

    private void jMenuItemEditarServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemEditarServicoActionPerformed
        GerenciarServicos telaServicos = new GerenciarServicos();
        telaServicos.setVisible(true);
    }//GEN-LAST:event_jMenuItemEditarServicoActionPerformed

    private void jMenuItemVisualizarServicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemVisualizarServicosActionPerformed
        ConsultarServicos telaConsultaServ = new ConsultarServicos();
        telaConsultaServ.setVisible(true);
    }//GEN-LAST:event_jMenuItemVisualizarServicosActionPerformed

    private void jMenuItemUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemUsuariosActionPerformed
        ConsultarUsuarios telaConsultaUsuarios = new ConsultarUsuarios();
        telaConsultaUsuarios.setVisible(true);
    }//GEN-LAST:event_jMenuItemUsuariosActionPerformed

    private void jMenuItemEditarPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemEditarPerfilActionPerformed
        EditarPerfil telaEditarPerfil = new EditarPerfil();
        telaEditarPerfil.setVisible(true);
    }//GEN-LAST:event_jMenuItemEditarPerfilActionPerformed

    private void jMenuItemGerarOrcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemGerarOrcActionPerformed
        // TODO add your handling code here:
        CadastroOrcamento telaCadastroOrc = new CadastroOrcamento();
        telaCadastroOrc.setVisible(true);
    }//GEN-LAST:event_jMenuItemGerarOrcActionPerformed

    private void jButtonLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLogoutActionPerformed
        int resposta = JOptionPane.showConfirmDialog(rootPane, "Deseja fazer logout?");
        if (resposta == JOptionPane.YES_OPTION) {
            loginService.logout();
            System.exit(0);
        } else {
            JOptionPane.showMessageDialog(rootPane, "Ação Cancelada.", "Logout", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jButtonLogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaAdm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonLogout;
    private javax.swing.JLabel jLabelLogotipo;
    private javax.swing.JLabel jLabelNomeUsuarioLogado;
    private javax.swing.JMenuBar jMenuBarAdministracao;
    private javax.swing.JMenu jMenuGerenciarServicos;
    private javax.swing.JMenuItem jMenuItemCadastrarUsuario;
    private javax.swing.JMenuItem jMenuItemEditarPerfil;
    private javax.swing.JMenuItem jMenuItemEditarServico;
    private javax.swing.JMenuItem jMenuItemGerarOrc;
    private javax.swing.JMenuItem jMenuItemListaOrcamentos;
    private javax.swing.JMenuItem jMenuItemUsuarios;
    private javax.swing.JMenuItem jMenuItemVisualizarServicos;
    private javax.swing.JMenu jMenuOrcamentos;
    private javax.swing.JMenu jMenuUsuarios;
    private javax.swing.JPanel jPanelTelaAdm;
    // End of variables declaration//GEN-END:variables
}
